pipeline {
    agent any
    environment {
        ARTIFACTORY_SERVER = 'rosario172.jfrog.io'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    def server = Artifactory.server(env.ARTIFACTORY_SERVER)
                    def rtGradle = Artifactory.newGradleBuild()
                    def buildInfo = Artifactory.newBuildInfo()

                    git branch: 'main', url: 'https://github.com/Rosariogorosito/gs-gradle.git'

                    rtGradle.tool = 'gradle'
                    rtGradle.deployer repo: 'default-gradle-dev-local', server: server
                    rtGradle.resolver repo: 'default-gradle-dev', server: server

                    stage('Configure buildInfo') {
                        buildInfo.env.capture = true
                        buildInfo.env.filter.addInclude("*")
                    }

                    stage('Additional Gradle Configurations') {
                        rtGradle.usesPlugin = true
                    }

                    stage('Execute Gradle') {
                        rtGradle.run rootDir: "artifactory/", tasks: 'clean artifactoryPublish', buildInfo: buildInfo
                    }

                    stage('Publish buildInfo') {
                        server.publishBuildInfo buildInfo
                    }
                }
            }
        }
    }
}
